### ISSUE TITLE
Copyq Clipboard Manager

### ISSUE THREAD

**Issue by vinzv** [siduction/pyfll#11]
Aus `base-xapps-debian`. 
Mindestens bei Plasma ist schon ein Clipboard Manager dabei. Und für die GTK ISOs würde ich was anderes wählen, weil die Abhängigkeiten schon umfangreich sind (QT libraries, KF5)

**Comment by fethomm** [comment]
Copyq kann man nicht mit dem integrierten Clipboard Manager vergleichen. Und ich kenne nichts Besseres, auch nicht für GTK. Ich hab natürlich keine Ahnung, wer das außer mir noch benutzt…

**Comment by vinzv** [comment]
Na dann lassen wir es mal drin.
