### ISSUE TITLE
Scanner-Unterstützung

### ISSUE THREAD

**Issue by vinzv** [siduction/pyfll#12]
`base-xapps-debian` bring xsane und sane mit. Ich persönlich nutze nie Scanner, daher würde ich mich da eher nach dem Urteil von anderen richten.

**Comment by fethomm** [comment]
xsane und sane sollten wohl bleiben, sind irgendwie basic.

**Comment by hhl** [comment]
mh, ich scanne noch gelegentlich, auch für viele Multifunktionsdrucker wird sane und xsane benötigt, sollte also bleiben.

**Comment by vinzv** [comment]
Okay, dann bleiben die beiden.
