### ISSUE TITLE
Kopete Chat

### ISSUE THREAD

**Issue by vinzv** [siduction/pyfll#17]
Aus `recommends`:
- nicht mehr in buster/testing/sid, aber in experimental
- Nur für XMPP wirklich relevant -> special interest tool?
- sollte eher in `env-kde`, vermutlich

**Comment by fethomm** [comment]
Wenn überhaupt, dann da.

**Comment by vinzv** [comment]
Ich finds nicht mehr, Stand https://github.com/siduction/pyfll/commit/c1e78be5458f0c1c9058120fc60a1c28e93b4844

Von daher erst mal zu.
