### ISSUE TITLE
Krusader Dateimanager

### ISSUE THREAD

**Issue by vinzv** [siduction/pyfll#22]
Aus `recommends`:
- nicht nötig für Non-QT ISOs
- Dolphin hat mittlerweile auch eine Split View -> krusader als special interest tool raus?

**Comment by fethomm** [comment]
Krusader wird von vielen geschätzt, die im Dateimanager als Root rumfuhrwerken.

**Comment by vinzv** [comment]
Pfui... aber gut, dann bleibt er eben drin. Ist eh in `env-kde` geschoben.
