### ISSUE TITLE
Mediaplayer-Wildwuchs

### ISSUE THREAD

**Issue by vinzv** [siduction/pyfll#23]
In `env-kde`:
- Kaffeine ist wohl für DVB praktisch -> special interest need
- @fethomm mag wohl smplayer, ich fahre mit [Haruna](https://invent.kde.org/multimedia/haruna) (MPV) ganz gut.
- smtube halte ich für unnötig -> special interest need
- Kaffeine vs. smplayer - wir sollten uns für eins entscheiden

**Comment by fethomm** [comment]
Kaffeine vs. smplayer ist in meinen Augen wie Äpfel und Birnen. Mit Kaffeine hatte ich noch nie gute Erfahrung mit Videos, ganz anders mit DVB-T, da hat es seine Stärken. Ich denke, da sollten beide bleiben.

**Comment by hhl** [comment]
Wird Kaffeine nicht automatisch mit plasma/kde installiert?

**Comment by vinzv** [comment]
Okay, Kaffeine und SMplayer bleiben. Smtube fliegt raus.
