### ISSUE TITLE
ligthtdm pakete

### ISSUE THREAD

**Issue by hhl** [siduction/pyfll#24]
Wir liefern immer noch lightdm Pakete aus, obwohl wir lightdm nicht mehr betreuen. Wir bauen mit jedem build wohl immer wieder sinnfrei nichtfunktionale lightdm-Pakete.
Da wären wintersky-, cblues, c-blues, paintitblack-lightdm .....
Diese sollten aus unseren quellen entfernt werden und wir müssten pyfll danach durchforsten!

Oder wir halsen uns noch Arbeit auf und betreuen lightdm wieder. Halte ich aber für sinnfrei.
Wir nutzen calamares, basierend auf qt, sddm ist qt, wir benötigen da keinen gtk basierenden dm zusätzlich.

**Comment by vinzv** [comment]
Ja, aber was ist mit Xfce? Da wäre der LightDM doch passender, oder?

**Comment by hhl** [comment]
mh, wir hatten mal gdm, lightdm-gtk und lightdm-qt, dann noch kdm und slim. Was eine Arbeit. Irgendwann haben wir beschlossen uns das Leben etwas einfacher zu machen, und da calamres qt basiert ist, warum dan nicht auch nur einen dm der qt basiert ist nutzen? Ich kann zwar mal schauen ob ich den lightdm noch verstehe und etwas machen kann. Das wird aber dauern, da mir gerade die Zeit etwas fehlt.
Solange sollten wir unsere lightdm Fake Pakete trotzdem entfernen, die sind in diesem Zustand in dem sie sich befinden Schrott und nur peinlich!
Wir können, wenn lightdm-siduction wieder funktioniert, jenen ja wieder ausliefern bzw. einbinden.

**Comment by vinzv** [comment]
Wenn ich richtig sehe ist lightdm in `blacklist`. Von daher hier erst mal zu.
