### ISSUE TITLE
CLI IRC Clients

### ISSUE THREAD

**Issue by vinzv** [siduction/pyfll#4]
`base-networking` bringt zwei CLI IRC Clients, zusätzlich zu den jeweiligen GUI Clients (Konversation, Hexchat):
- irssi
- irssi-scripts
- weechat
- weechat-scripts

**Comment by hhl** [comment]
Mir persönlich würde ja weechat reichen, aber es gibt da Spezialisten, die wollen unbedingt irssi.
Und ein clientCLI IRC-Client ist schon nützlich, wenn X11/Wayland seine Dienste verweigert oder man aus init 3 heraus Hilfe benötigt.

**Comment by vinzv** [comment]
Jo, dann bleibts
