### ISSUE TITLE
Screenshooter

### ISSUE THREAD

**Issue by vinzv** [siduction/pyfll#8]
Aus `base-xapps-debian`:
- scrot
- flameshot

Vorschlag: Für GUI ISOs Flameshot nehmen, für nox bei scrot belassen. Aber nicht beides in allen ISOs.

**Comment by fethomm** [comment]
Da bin ich bei dir.

**Comment by vinzv** [comment]
Jut, wird so gemacht. https://github.com/siduction/pyfll/pull/26/commits/4783b94768f87a12c35eca56ef7bf4f3b3d75493
